version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rickandmortyisntfunny
    ports:
      - "27018:27017"
    volumes:
      - /home/volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network
networks: 
  mongo-compose-network:
    driver: bridge